package: quark-assistant
paths:
  prompts: "config/quark-assistant/prompts/{prompt}.yaml"
  toolsets: "config/quark-assistant/toolsets/{toolset}.yaml"
  query: 'datastores/query'
vendors:
  - aws
  - azure
  - google
agents:
  summarizer:
    vendor: aws
    prompt: summarizer
  default: 
    vendor: aws
    prompt: default
  image-gen: 
    vendor: aws
    prompt: image-gen
 #task-handler: 
  task-handler-v0: 
    vendor: aws
    prompt: task-handler
  validation: 
    vendor: aws
  qa: 
    vendor: aws
    prompt: qa
  text-gen: 
    vendor: aws
    prompt: text-gen
  re-bc5cdr: 
    vendor: aws
    prompt: re-bc5cdr
  re-ddi: 
    vendor: aws
    prompt: re-ddi
  ncbi: 
    vendor: aws
    prompt: ncbi
    toolset: eutils
  developer: 
    vendor: aws
    prompt: code-gen
  nomenclator-title: 
    vendor: aws
    prompt: nomenclator-title
#   parameters:
#     temperature: 
#     max_tokens: 
#     stop_sequences:
#     top_p:

  log-analyzer:
    vendor: aws
    prompt: log-analyzer
    parameters:
     temperature: 0.0 

models:
  aws: 
    name: "apac.amazon.nova-micro-v1:0"
    values: {}
  azure: 
    name: azure-gpt-v3.5turbo
    values:
      azure_endpoint: https://openai-inv.openai.azure.com/
      azure_deployment: openai-chatgpt-test
      api_version: 2024-05-01-preview
  google:
    name: gemini-1.5-pro-002
    values:
      project_id: dark-matter-mpv-v1
storages:
  s3:
    enabled: true
    config: {}
    stores:
      myfiles: "s3://artifacts02/artifacts/{user}/{project}/uploads"
      #add support for other datalocations through opensearch index
  # opensearch:
  #   enabled: true
  #   config:
  #     hosts: http://localhost:9200
  #     http_auth:
  #       - admin
  #       - Invisibl*123
  #   stores:
  #     users: projectmembers-dev
  #     messages: messages-dev
  #     embeddings: embeddings-dev
  #     prompts: prompts-dev
  #     memories: memories-dev
  #     datalocations: datalocations-dev
  #     knowledgebases: knowledgebases-dev
knowledgestores:
  opensearch:
    retriever: 
      type: bm25
      config: {}
    document_store: 
      config: {}
    embedder:
      sentencetransformer: {}
      azure:
        azure_endpoint: https://openai-inv.openai.azure.com/
        azure_deployment: openai-embedding

# knowledge_graph:
#   schema:
#     location: "C:/invisibl/quark-assistant/datastores/neptune/schema.yaml"
#   gtex:
  
#     entities:
#       entities_path: "C:/Users/priya/Downloads/csvs"  
#       entities_file_type: "csv"  
knowledge_graph:
  schema:
    location: "datastores/neptune/schema.yaml"
  gtex:
    entities:
      entities_path: "datastores/neptune/gtex/data/biocypher"
      entities_file_type: "csv"
    ner_path: "datastores/neptune/gtex/en_core_sci_sm-0.5.4/en_core_sci_sm/en_core_sci_sm-0.5.4"
    graph_db:
      endpoint: "https://db-neptune-1-instance-1.cigfmmqgs6p9.us-east-1.neptune.amazonaws.com:8182"

