apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quark-assistant.fullname" . }}
  labels:
    {{- include "quark-assistant.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
