---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quark-assistant.fullname" . }}
  labels:
    {{- include "quark-assistant.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.apiserver.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "quark-assistant.selectorLabels" . | nindent 4 }}
