{{- if and .Values.rbac.enabled (not .Values.rbac.namespaced) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "quark-assistant.fullname" . }}
  labels:
    {{- include "quark-assistant.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "quark-assistant.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "quark-assistant.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
